/** Edit this file to personalize every word and setting on the site. */
export const site = {
  partner: 'Sumaya Sikder Tuly',
  from: 'Shiam Sharif',
  birthday: '18 September 2003',
  celebration: '18 September 2026',
  age: 23,
  music: { src: '/audio/happy-birthday.mp3', loop: false },
  invitation: {
    eyebrow: 'A little surprise for my favourite person.',
    title: '100 little moments. One very special you.',
  },
  hero: {
    eyebrow: 'Today is all about you',
    title: 'Happy 23rd Birthday,',
    subtitle: 'The world became a little more beautiful on 18 September 2003.',
  },
  story: {
    title: 'So many moments. So many reasons to smile.',
    subtitle: 'A little collection of you, seen through my eyes.',
  },
  gallery: {
    title: 'The little things, forever kept.',
    subtitle: 'Every photograph holds a piece of your magic.',
  },
  loveNotes: [
  'I love your personality.',
  'The way your laughter makes everything feel lighter.',
  'How you make ordinary moments feel special.',
  'I love your beautiful eyes and the way they light up when you smile.',
  'Your beautiful, thoughtful heart.',
  'The way you keep becoming more yourself.',
  'I love your way of talking.',
  'Your thoughts, your vision, your energy, and the way you never give up.',
  'Your little smiles when you are happy.',
  'You opened my eyes and made even the road to camp feel beautiful.',
  'The way you listen with your whole heart.',
  'Your courage, even on difficult days.',
  'How you find beauty in small things.',
  'Your gentle honesty.',
  'The dreams you hold close.',
  'How you make me want to be better.',
  'Your playful side.',
  'The comfort of simply being with you.',
  'Your strength and your softness.',
  'The way you care so deeply, even when you never admit it to me.',
  'All the little things that make you you.',
  'Every version of you I have had the joy to know.',
  'The thought of all the tomorrows still ahead of us.',
],
  letter: [
    'My Sumu❤️,',
    'Happy 23rd birthday.',
    'I wanted to make something that you could come back to whenever you wanted a little place filled with your smile, your photos, and a reminder of how much you mean to me.',
    'Even with all these pictures, there is still so much about you that a photograph cannot capture. Your kindness, your laughter, and the little things that make you who you are mean more to me than I can explain.',
    'I hope this year brings you happiness, peace, exciting beginnings, and the courage to follow your dreams. I hope you feel celebrated today, and loved every day after it.',
    'Thank you for being you Kuntuku❤️.',
    'Happy birthday, my favourite person❤️.',
  ],
  wish: 'May this year bring you closer to everything your heart wishes for. ❤️',
  final: 'Of all these beautiful memories, my favourite thought is that there are still more to come with you.',
  portfolio: {
    message: 'I made one more thing for you: your very own portfolio website. A little space for your dreams, your work, and everything still ahead.',
    url: 'https://sumaya-sikder-tuly.netlify.app/',
    buttonLabel: 'Visit your portfolio',
  },
} as const;
